### PR TITLE
Fixed conf.php for current ganglia web

### PR DESCRIPTION
**Pull request by NoodlesNZ**
Quick fix for conf.php. I'm not sure if it's worth copying all of the options over from the default_conf.php as it means keeping the template up to date with any changes.

### CODE REVIEW

**Comment by jhoblitt** [comment]
@NoodlesNZ This looks good.  I discovered this myself right after I cut the 2.0.0 release and wasn't sure what to do about it.  Do you think this should be a major version bump or 2.1.0?

**Comment by NoodlesNZ** [comment]
Thanks for that @jhoblitt . Probably just a 2.1.0 release, if you can hold off I'll push another PR today to add rrdcached socket into ganglia web (something I had to add recently as RRD was killing my ganglia box).

**Comment by jhoblitt** [comment]
@NoodlesNZ Sure - no rush on my part.

**Comment by jhoblitt** [comment]
Release as v2.1.0: https://forge.puppetlabs.com/jhoblitt/ganglia/2.1.0

**Comment by NoodlesNZ** [comment]
Doh, I forgot about this. Thanks for the release Josh

**Pull request merged**
