### PR TITLE
PDK Convert & Some tests passing on Puppet 6

### PR DESCRIPTION
**Pull request by frizop**

### CODE REVIEW

**Comment by jhoblitt** [comment]
I really appreciate the effort that's going into this PR. Could someone explicitly ping me when it is ready for merge in case I miss the title being updated?

**Comment by frizop** [comment]
@jhoblitt no problem, just pinging you now that all tests pass! Quite welcome on the effort. I think one of the last things is to figure out what we're going to support in terms of OS versions..

**Comment by frizop** [comment]
Alright, I think that's it. @jhoblitt I did end up doing some more to the module to clean things up like added `@param` options to the class docs. I accidentally wiped out your previous commit/PR (and then added the stuff back in) as follows:
```
commit 9460bdc70bfb4ca831d7fe57154fcb73c792fb08
Author: Rike-Benjamin Schuppner <rikebs@debilski.de>
```
So I just pushed up a cherry-pick to make sure that it is contained in the repo. Apologies for that.

**Comment by jhoblitt** [comment]
I would be fine with making a major version bump and dropping anything older than rhel/centos 7.

**Comment by jhoblitt** [comment]
@frizop I'll take a detailed look once CI passes.  Could I ask you to do a rebase to remove the merge commit?

**Comment by frizop** [comment]
> @frizop I'll take a detailed look once CI passes. Could I ask you to do a rebase to remove the merge commit?

Sure thing. Give me a minute and I'll push that up

**Comment by frizop** [comment]
Sadly I had to force push again because that merge got involved. Let me know if this looks good for you @jhoblitt

**Comment by jhoblitt** [comment]
This looks great. Thank you for putting all the effort into this!

**Pull request merged**
