### PR TITLE
Add params for optional gmond-python (by default not installed)

### PR DESCRIPTION
**Pull request by jcpunk**
This PR adds the option to also install the gmond-python package if you desire.  Two params were added to `ganglia::gmond` to permit installation of the optional python libraries.

By default they are not installed to preserve existing behavior.

### CODE REVIEW

**Comment by jhoblitt** [comment]
Ugh - the travis / unit testing config needs TLC.

**Comment by jhoblitt** [comment]
@jcpunk Are you still using this mod?

**Comment by jcpunk** [comment]
I am.  I'm actually still using the old version this patch applied against.  It met my needs so I didn't update the module when you pushed new versions.

**Review by jhoblitt — APPROVED** [review]
This LGTM but I'll note there are no tests.  This has been open for so long I'm inclined to accept it without raising the bar.  @frizop what do you think?

**Comment by frizop** [comment]
Ok, so this is kinda interesting in that we do param checking for the following:
```
Variant[String, Tuple] $gmond_package_name        = $ganglia::params::gmond_package_name,
```
so you can pass a single string in there, or a `['package1', 'package2']` and some of the tests iirc, do catch that. Let me see if I can figure out which one it is.

**Comment by frizop** [comment]
`gmond_spec.rb:119` should cover multiple package names

**Comment by frizop** [comment]
yeah, I don't think we need this unless we want to call out a totally separate class param for extra packages... I'm not totally opposed to including something like, 
    
    Array $extra_packages = $ganglia::params::extra_packages

with a default value of `[]`

**Pull request closed without merging**
