### PR TITLE
Add metadata.json to git

### PR DESCRIPTION
**Pull request by NoodlesNZ**
Add metadata.json to git
Bump to version 1.4.0
Add os support

### CODE REVIEW

**Comment by NoodlesNZ** [comment]
Rolled back unrelated changes. Was trying to fix CI, but was unsuccessful.

**Comment by jhoblitt** [comment]
I replaced `Modulefile` with `metadata.json` as part of #40, so this PR has been obsoleted.

**Comment by NoodlesNZ** [comment]
Thanks Josh, good work. I couldn't get it building on those two older instances, what was the trick? Good to see you've updated forge as well :)

**Comment by jhoblitt** [comment]
The Encoding gem setup in spec_helper.rb needed to be setup.

**Pull request closed without merging**
